### ISSUE TITLE
Installation on Titan failed with "ImportError: No module named vtkRenderingOpenGLPython"

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#119]
More information:
```
Error in acme_diags.driver.zonal_mean_xy_driver
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/acme_diags-1.1.1-py2.7.egg-info/scripts/acme_diags_driver.py", line 56, in run_diag
    module = importlib.import_module(mod_str)
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/acme_diags/driver/zonal_mean_xy_driver.py", line 8, in <module>
    from acme_diags.plot import plot
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/acme_diags/plot/__init__.py", line 11, in <module>
    from vcs.colors import matplotlib2vcs
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/vcs/__init__.py", line 92, in <module>
    from utils import *  # noqa
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/vcs/utils.py", line 38, in <module>
    import vtk
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/vtk/__init__.py", line 88, in <module>
    from .vtkRenderingOpenGL import *
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/vtk/vtkRenderingOpenGL.py", line 9, in <module>
    from vtkRenderingOpenGLPython import *
ImportError: No module named vtkRenderingOpenGLPython
(acme_diags_env) zhang40@titan-ext5:~/acme_diags/tests> acme_diags_driver.py -d all_sets.cfg --backend mpl
Error in acme_diags.driver.zonal_mean_xy_driver
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/acme_diags-1.1.1-py2.7.egg-info/scripts/acme_diags_driver.py", line 56, in run_diag
    module = importlib.import_module(mod_str)
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/acme_diags/driver/zonal_mean_xy_driver.py", line 8, in <module>
    from acme_diags.plot import plot
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/acme_diags/plot/__init__.py", line 11, in <module>
    from vcs.colors import matplotlib2vcs
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/vcs/__init__.py", line 92, in <module>
    from utils import *  # noqa
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/vcs/utils.py", line 38, in <module>
    import vtk
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/vtk/__init__.py", line 88, in <module>
    from .vtkRenderingOpenGL import *
  File "/ccs/home/zhang40/anaconda3/envs/acme_diags_env/lib/python2.7/site-packages/vtk/vtkRenderingOpenGL.py", line 9, in <module>
    from vtkRenderingOpenGLPython import *
ImportError: No module named vtkRenderingOpenGLPython
```

```
(acme_diags_env) zhang40@titan-ext5:~/acme_diags/tests> conda list vtk
# packages in environment at /ccs/home/zhang40/anaconda3/envs/acme_diags_env:
#
vtk-cdat                  7.1.0.2.12      py27_mesalibh6bab67e_0  [mesalib]  uvcdat
(acme_diags_env) zhang40@titan-ext5:~/acme_diags/tests> conda list ffmpeg
# packages in environment at /ccs/home/zhang40/anaconda3/envs/acme_diags_env:
#
ffmpeg                    3.2.4                         1    conda-forge
```

**Comment by chengzhuzhang** [comment]
Titan is really not an analysis machine. We are using Rhea instead.
