### ISSUE TITLE
acme_viewer error after all runs completed

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#138]
@whannah1 encountered this issue on Rhea after all runs finishes. 

And Jill reproduced this error on AIMS4, error info as follows:
```python
Traceback (most recent call last):
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/bin/acme_diags_driver.py", line 4, in <module>
    __import__('pkg_resources').run_script('acme-diags==1.2.1', 'acme_diags_driver.py')
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/acme_diags-1.2.1-py2.7.egg/EGG-INFO/scripts/acme_diags_driver.py", line 140, in <module>
    create_viewer(pth, parameters, parameters[0].output_format[0])
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/acme_diags-1.2.1-py2.7.egg/acme_diags/acme_viewer.py", line 613, in create_viewer
    viewer.generate_viewer(prompt_user=False)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/cdp-1.2.3-py2.7.egg/cdp/cdp_viewer.py", line 90, in generate_viewer
    default_mask=default_mask)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/output_viewer/build.py", line 65, in build_viewer
    page.build(page_name, toolbar)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/output_viewer/page.py", line 256, in build
    group_obj.build(toolbar)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/output_viewer/page.py", line 157, in build
    r.build(toolbar)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/output_viewer/page.py", line 137, in build
    col.build(toolbar)
  File "/export_2/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/output_viewer/page.py", line 43, in build
    n = doc.append_tag("form", action=self.row.cols[col_ind + 1].getFileName(), class_="col_link next")
```

**Comment by chengzhuzhang** [comment]
Same error occurs with the simulation we usually test (20161118.beta0.FC5COSP.ne30_ne30.edison) with. Below is the parameter file

```python
reference_data_path = '/p/cscratch/acme/data/obs_for_acme_diags/'
#test_name = 'ACME_ZM_CTL_ne30_00'

test_data_path = '/p/cscratch/acme/data/test_model_data_for_acme_diags/'
test_name = '20161118.beta0.FC5COSP.ne30_ne30.edison'


#test_data_path      = '/p/cscratch/acme/zhang40/data_hannah/'+test_name+'/climo_rgr/'
sets = ["lat_lon","zonal_mean_2d","zonal_mean_xy"]


backend = 'mpl'  # 'mpl' is for the matplotlib plots - faster than vcs
# backend = 'vcs'

results_dir = 'results_lat_lon_'+test_name

if "_SP1" in test_name :
        diff_title = 'SP-E3SM - Obs'
        # results_dir = 'E3SM_SP1_all'  # name of folder where all results will be stored

if "_SP2" in test_name :
        diff_title = 'SP-E3SM - Obs'
        # results_dir = 'E3SM_SP2_all'  # name of folder where all results will be stored

if "_ZM" in test_name :
        diff_title = 'E3SM - Obs'
        # results_dir = 'E3SM_ZM_all'  # name of folder where all results will be stored

seasons = ['ANN',"DJF","JJA"]


multiprocessing = True
num_workers = 16
```

**Comment by zshaheen** [comment]
Use this to recreate the run with Walter's data on aims4/acme1.

```
# reference_data_path = '/global/project/projectdirs/acme/acme_diags/obs_for_acme_diags/'
# reference_data_path = '/lustre/atlas/proj-shared/csc249/hannah6/ACME/obs_for_acme_diags/'

# ref_name = 'ERA-Interim'
# reference_data_path = '/ccs/proj/cli115/acme_diags_data/obs_for_acme_diags/'
reference_data_path = '/p/cscratch/acme/data/obs_for_acme_diags/'



# test_name = 'ACME_SP1_CTL_ne30_32x1_1km_00'
# test_name = 'ACME_SP1_CTL_ne30_32x1_1km_s2_65'
test_name = 'ACME_ZM_CTL_ne30_00'
# test_name = 'ACME_ZM_CTL_ne30_25'

# test_data_path      = '/lustre/atlas/proj-shared/cli115/hannah6/ACME/ACME_SP1_CTL_ne30_32x1_1km_00/climo/'
# test_data_path      = '/lustre/atlas/proj-shared/cli115/hannah6/ACME/ACME_ZM_CTL_ne30_00/climo/'
# test_data_path      = '/lustre/atlas/proj-shared/cli115/hannah6/ACME/'+test_name+'/climo_rgr/'
test_data_path      = '/p/cscratch/acme/zhang40/data_hannah/'+test_name+'/climo_rgr/'



# sets = ["lat_lon"]
# sets = ["zonal_mean_2d"]
# sets = ["zonal_mean_xy"]

sets = ["lat_lon","zonal_mean_2d","zonal_mean_xy"]
# sets = ["lat_lon_sat"]

#----------------------------
# optional settings below
#----------------------------
# diff_title = 'Model - Obs'


backend = 'mpl'  # 'mpl' is for the matplotlib plots - faster than vcs
# backend = 'vcs'

results_dir = 'results_'+test_name

if "_SP1" in test_name :
	diff_title = 'SP-E3SM - Obs'
	# results_dir = 'E3SM_SP1_all'  # name of folder where all results will be stored

if "_SP2" in test_name :
	diff_title = 'SP-E3SM - Obs'
	# results_dir = 'E3SM_SP2_all'  # name of folder where all results will be stored

if "_ZM" in test_name :
	diff_title = 'E3SM - Obs'
	# results_dir = 'E3SM_ZM_all'  # name of folder where all results will be stored

seasons = ['ANN',"DJF","JJA"]
# regions = ["global"]


multiprocessing = True
num_workers = 25
```

**Comment by chengzhuzhang** [comment]
@zshaheen tested master. Totally worked and results make sense. Let's talk about the commit tomorrow. 

What a journey tracking down this well-hidden bug...
