### ISSUE TITLE
Add command line arguments

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#46]
So that this can easily be used in the ACME Workflow.
Maybe we don't need to add all of the arguments, just the ones that are defined in ACMEParameter.

**Comment by sterlingbaldwin** [comment]
This isnt that important to me actually, I have no problem generating the parameters file. That said, however you're doing argument parsing should be updated to no crash when you dont give it the arguments its expecting. Right now if you just call acme_diags_driver.py with nothing it does this:

```
(workflow) -bash-4.1$ acme_diags_driver.py 
Traceback (most recent call last):
  File "/export/baldwin32/anaconda2/envs/workflow/bin/acme_diags_driver.py", line 4, in <module>
    __import__('pkg_resources').run_script('acme-diags==0.1', 'acme_diags_driver.py')
  File "/export/baldwin32/anaconda2/envs/workflow/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/export/baldwin32/anaconda2/envs/workflow/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/export/baldwin32/anaconda2/envs/workflow/lib/python2.7/site-packages/acme_diags-0.1-py2.7.egg-info/scripts/acme_diags_driver.py", line 48, in <module>
    original_parameter = parser.get_parameter(default_vars=False)
  File "/export/baldwin32/anaconda2/envs/workflow/lib/python2.7/site-packages/cdp/cdp_parser.py", line 37, in get_parameter
    self._parameter.check_values()
  File "/export/baldwin32/anaconda2/envs/workflow/lib/python2.7/site-packages/acme_diags/acme_parameter.py", line 58, in check_values
    if self.reference_data_path == '':
AttributeError: 'ACMEParameter' object has no attribute 'reference_data_path'
```

Im not sure what the cdp.parser uses under the hood, but argparse has a nice parser.print_help() method that I use like this:

```
if not args.config:
    parser.print_help()
    sys.exit()
```

**Comment by zshaheen** [comment]
Yup, that's what #36 is about.

**Comment by sterlingbaldwin** [comment]
Ah cool, didnt see it there.

**Comment by zshaheen** [comment]
Done in fbf83700cc45020ebefaff364ec42dd27a8a79e7
